### ISSUE TITLE
Questions about Item

### ISSUE THREAD

**Issue by Yufanggg** [antovis86/lmeEEG#1]
Heyy, you mentioned in the paper that you included two random variables. However, in the code, I only saw one random variable, i.e., subject.

**Comment by antovis86** [comment]
Dear Yufanggg,
In our code, we indeed include random intercepts for both subjects (ID) and items. You can find this specified in line 10 of the **lmeEEG_tutorial.mlx** file as follows:

``m = fitlme(EEG,'EEG~CON+(1|**ID**)+(1|**Item**)');

I hope this clarification addresses your concern. If you have any further questions or need additional information, please don't hesitate to ask.

Best regards,
Antonino

**Comment by Yufanggg** [comment]
Thank you for your reply. However, 
uiopen('...\lmeEEG_tutorial.mlx',1)
Caught "std::exception" Exception message is:
MATLAB Code not found

was reported.

**Comment by Yufanggg** [comment]
can you save the .mlx file into m and reupload it again? It is not able to open.
